server:
  port: 8085

spring:
  application:
    name: search-service
  datasource:
    url: jdbc:mysql://localhost:3306/mall_search?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: "123456"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
